### ISSUE TITLE
一个奇怪的问题

### ISSUE THREAD

**Issue by amhoho** [zoujingli/WeChatDeveloper#10]
发现一个奇怪的问题,用最新版覆盖后,整个就不工作了.必须注释这样的:`throw new InvalidResponseException($e->getMessage(), $e->getCode());`,才能正常工作?是什么原因呢?linux+php5.6.

**Comment by zoujingli** [comment]
建立不要使用ComposerUpdate去更新代码

**Comment by amhoho** [comment]
正是Composer的,不行后直接下载解压,结果一样报错.只有注释以上这些行后正常.

**Comment by amhoho** [comment]
所有,比如:
`
    protected function httpGetForJson($url)
    {
        try {
            return Tools::json2arr(Tools::get($url));
        } catch (InvalidResponseException $e) {
            if (!$this->isTry && in_array($e->getCode(), ['40014', '40001', '41001', '42001'])) {
                $this->delAccessToken();
                $this->isTry = true;
                return call_user_func_array([$this, $this->currentMethod['method']], $this->currentMethod['arguments']);
            }
//必须注释下一行才可以
           // throw new InvalidResponseException($e->getMessage(), $e->getCode());
        }
    }
`

**Comment by zoujingli** [comment]
可能是接口返回的值少了什么字段，需要具体调试下
