### ISSUE TITLE
最近微信支付爆出xml实体注入XXE漏洞

### ISSUE THREAD

**Issue by u0mo5** [zoujingli/WeChatDeveloper#11]
能针对此问题更新下嘛？

**Comment by u0mo5** [comment]
/**
     * 解析XML内容到数组
     * @param string $xml
     * @return array
     */
    public static function xml2arr($xml)
    {
        $disableLibxmlEntityLoader = libxml_disable_entity_loader(true);
        $array_data = json_decode(self::arr2json(simplexml_load_string($xml, 'SimpleXMLElement', LIBXML_NOCDATA)), true);
        libxml_disable_entity_loader($disableLibxmlEntityLoader);
        return $array_data;
    }

**Comment by zoujingli** [comment]
收到，下个版本会加入这段代码
谢谢

**Comment by zoujingli** [comment]
代码已经提交
