### ISSUE TITLE
关于获取AccessToken方法的修改建议

### ISSUE THREAD

**Issue by shenfeng07** [zoujingli/WeChatDeveloper#14]
/**
     * 通过 code 获取 AccessToken 和 openid
     * @return bool|array
     * @throws Exceptions\InvalidResponseException
     */
    public function getOauthAccessToken()
    {
        $appid = $this->config->get('appid');
        $appsecret = $this->config->get('appsecret');
        $code = isset($_GET['code']) ? $_GET['code'] : '';
        $url = "https://api.weixin.qq.com/sns/oauth2/access_token?appid={$appid}&secret={$appsecret}&code={$code}&grant_type=authorization_code";
        return $this->httpGetForJson($url);
    }

建议这个方法用到的code能可以改成使用参数传递。在前后端完全分离开发时，code不一定是通过get方法提交的，用参数传递会比较灵活。

**Comment by zoujingli** [comment]
直接设置 $_GET 再调用此方法，通常情况下，这个还是以get访问为主

**Comment by wenmingtang** [comment]
```php
$_GET['code'] = $code; // 该库的作者完全没有脑子，导致只能复制全局变量传参
$access = WechatService::WeChatOauth()->getOauthAccessToken();
```
