### ISSUE TITLE
支付宝当面付API问题

### ISSUE THREAD

**Issue by hanlhan** [zoujingli/WeChatDeveloper#17]
我在测试当面付时，出现这个错误

ResultError
Service Currently Unavailable[20000]
系统繁忙[aop.unknow-error]

经过查找和百度，应该是和支付宝服务器的连接方式问题。

BasicAliPay.php 199 行

`$data = json_decode(Tools::post($this->gateway, $this->options->get()), true);`

你是用post方式提交的

我改为 get 方式提交后错误消失了。

`$data = json_decode(Tools::get($this->gateway, $this->options->get()), true);`

不知道是不是这个问题，改的对不对，希望你看一下。

**Comment by zoujingli** [comment]
是沙箱模式吗？方便提供下测试参数吗？

**Comment by zoujingli** [comment]
已经解决
