### ISSUE TITLE
支付宝网站支付问题

### ISSUE THREAD

**Issue by hanlhan** [zoujingli/WeChatDeveloper#19]
首先，很感谢你写的这套sdk。

支付宝 pc 端支付代码有一点问题。

刚开始的时候直接使用你的代码，出现缺少‘method’错误：

`错误代码 missing-method 错误原因: 缺少方法名参数`

支付宝配置和商品描述都没有问题，使用的是正式环境。

后来我下载官方的demo，比较你生成的html和他们生成的html代码，发现你生成的代码 input 少了很多参数，原来你就把 params 参数放进去了，option里面的参数没有加进去。

我直接在下面加了一个循环（vendor\zoujingli\wechat-developer\WeChat\Contracts\BasicAliPay.php：226行左右）

```
foreach ($this->options->get() as $key => $value) {
            $value = str_replace("'", '&apos;', $value);
            $html .= "<input type='hidden' name='{$key}' value='{$value}'/>";
        }
```

出现验签错误：

`错误代码 invalid-signature 错误原因: 验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：`

仔细比较生成的html代码，原来 product_code 参数是放在 biz_content 参数里面的。

最终修改如下：
vendor\zoujingli\wechat-developer\WeChat\Contracts\BasicAliPay.php 186行：
```
$this->options['biz_content'] = json_encode(array_merge($options, $this->params->get()), 
JSON_UNESCAPED_UNICODE);
```

222 行 ：
```
// foreach ($this->params->get() as $key => $value) {
        //     $value = str_replace("'", '&apos;', $value);
        //     $html .= "<input type='hidden' name='{$key}' value='{$value}'/>";
        // }
        foreach ($this->options->get() as $key => $value) {
            $value = str_replace("'", '&apos;', $value);
            $html .= "<input type='hidden' name='{$key}' value='{$value}'/>";
        }
```

成功调起支付宝pc支付界面。

其他模式未测试。

**Comment by zoujingli** [comment]
非常感谢您的反馈，我也试着改了下。
我是用沙箱测试的，有时候不够准确，还请多包涵。
针对您反馈的内容，我进行了修改，也请帮忙度下，沙箱试着是可以的

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/48405128-affedd80-e76c-11e8-9f3d-1484400900ed.png)

**Comment by feverrun** [comment]
楼主反应的问题， 我也遇到了， 谢谢
