### ISSUE TITLE
统一订单和 JSAPI 的签名算法不同导致 chooseWXPay 调用失败？

### ISSUE THREAD

**Issue by LLoyou00** [zoujingli/WeChatDeveloper#2]
这个版本的 Pay.php 创建预支付订单使用的默认签名算法和生成支付签名的所使用的默认签名算法不一样，而这可能会导致调用 chooseWXPay 时报签名错误。
![_20180430001523](https://user-images.githubusercontent.com/9455777/39408617-a4aa2770-4c0b-11e8-89e5-8efad66dd30a.png)
![_20180430001541](https://user-images.githubusercontent.com/9455777/39408618-a6297a4c-4c0b-11e8-8fec-55667b50fce1.png)
创建预支付订单默认使用的是 HMAC-SHA256 算法

- 

- 

![_20180430001651](https://user-images.githubusercontent.com/9455777/39408630-cfbc3246-4c0b-11e8-8ea1-6dd769f34472.png)
生成支付签名默认使用的是 MD5 算法

微信的文档里面似乎也没有提到这两者的不一致会导致签名验证失败，我在调用 getPaySign 是指定使用 HMAC-SHA256 算法， chooseWXPay 顺利调用。

不知道这里面是否有什么误会。如果确实是因为两个地方使用的算法不一样而导致签名验证失败，希望作者能将两者的算法改成一样。
因为。。。。微信的文档真的太难读了！！！。。。。我试了一整天才发现这个现象。

**Comment by zoujingli** [comment]
您好，
JSAPI签名不是用这个的，需要另外再生成
这个option就是jsapi需要的参数和签名，
不过，在WechatDeveloper 中 签名需要调用 getPaySign($option,'MD5');



zoujingli@qq.com
 
发件人： LLoyou00
发送时间： 2018-04-30 00:23
收件人： zoujingli/WeChatDeveloper
抄送： Subscribed
主题： [zoujingli/WeChatDeveloper] 统一订单和 JSAPI 的签名算法不同导致 chooseWXPay 调用失败？ (#2)
这个版本的 Pay.php 创建预支付订单使用的默认签名算法和生成支付签名的所使用的默认签名算法不一样，而这可能会导致调用 chooseWXPay 时报签名错误。


创建预支付订单默认使用的是 HMAC-SHA256 算法

生成支付签名默认使用的是 MD5 算法
微信的文档里面似乎也没有提到这两者的不一致会导致签名验证失败，我在调用 getPaySign 是指定使用 HMAC-SHA256 算法， chooseWXPay 顺利调用。
不知道这里面是否有什么误会。如果确实是因为两个地方使用的算法不一样而导致签名验证失败，希望作者能将两者的算法改成一样。
因为。。。。微信的文档真的太难读了！！！。。。。我试了一整天才发现这个现象。

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/39502031-bad91f9c-4df0-11e8-9087-7d6073dd9617.png)

**Comment by LLoyou00** [comment]
@zoujingli 好的，Thank you.
另外就是我们这边有些业务需求需要用到微信支付的退款功能，看了下源代码，不是很能理解要怎么做，看云上的付费文档也没有详细的说明，不知道您这边是否能给个例子呢。

**Comment by zoujingli** [comment]
传订单号进去，要退的金额，原交易金额

**Comment by LLoyou00** [comment]
@zoujingli 好的，我可能没有表达清楚。
我的疑惑点主要在于 RSA 密钥要怎么设置。
这边的 options 要怎么传递进去
![tim 20180502102256](https://user-images.githubusercontent.com/9455777/39502531-57a02ddc-4df3-11e8-9049-04fe71a57430.png)

- 
以及这边的密钥文件要放在哪儿
![tim 20180502102636](https://user-images.githubusercontent.com/9455777/39502550-6f69db2a-4df3-11e8-94fc-ef2f0084fbc9.png)

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/39502598-aa5fd84c-4df3-11e8-8a2b-37f87eae7833.png)
这些你不用管，只需要配置好参数就行了

**Comment by LLoyou00** [comment]
好的，我试试看

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/39502633-cfb85966-4df3-11e8-9075-adead99c1a47.png)
    'ssl_key'        => '',
    'ssl_cer'        => '',
这两个参数配证书的目录，最好是绝对目录

**Comment by LLoyou00** [comment]
好的，Thank you.
