### ISSUE TITLE
php 5.6 微信错误 麻烦修复

### ISSUE THREAD

**Issue by lixiaolong2** [zoujingli/WeChatDeveloper#21]
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in E:\xampp\htdocs\TWCloud\vendor\zoujingli\wechat-developer\WeChat\Contracts\Tools.php on line 277

\zoujingli\wechat-developer\WeChat\Contracts\Tools.php 

第277行              $data[$key] = ($myCurlFile = new MyCurlFile((array)$value))->get();

修改为 
$myCurlFile = new MyCurlFile((array)$value);
 $data[$key] = $myCurlFile->get();

**Comment by zoujingli** [comment]
已经修复
