### ISSUE TITLE
验签失败仍转账成功

### ISSUE THREAD

**Issue by yew30** [zoujingli/WeChatDeveloper#23]
支付宝AliPayTransfer()接口，public_key没有使用支付宝的公共key，用了自己的key，提示“Data signature verification failed”，这个是正确的。但是看转账记录，却发现转账成功了。是不是应该修复一下，这个时候不给转账。

**Comment by zoujingli** [comment]
public_key验证返回的结果是否正确，由于public_key错了，返回的结果自然是无法识别的。
请使用正确的public_key值，这个key需要到支付网页中获取

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/50754986-7f31b500-1292-11e9-874d-b0685086cf59.png)

**Comment by yew30** [comment]
是的，返回错误信息这个是对的。但是返回错误信息时，转账还是成功的，这个要阻止一下。

**Comment by yew30** [comment]
就是说，虽然提示了验签错误，但是转账仍然发生了。

**Comment by zoujingli** [comment]
这是两个操作，提交操作成功，返回结果验证失败（实际是成功的）
