### ISSUE TITLE
Tools::arr2json 能否加参数，不转移Emoji标签

### ISSUE THREAD

**Issue by moufer** [zoujingli/WeChatDeveloper#28]
因为数据表里都是utf8mb4保存的，在提取后用客户消息时，会被Tools::emojiEncode转义，导致用户收到的都是\uexxxx码，Custom::send里也不支持直接发送自己的json，而一定要数组才行，好像只能继承类，覆盖send函数，弃用httpPostForJson，但发现httpPostForJson使用的地方很多不清楚会不会还有其他地方会涉及到。

**Comment by zoujingli** [comment]
取出来之前可以进行一次解码
