### ISSUE TITLE
开放平台获取access_token的时候提示 ticket 不对

### ISSUE THREAD

**Issue by Abyss1st** [zoujingli/WeChatDeveloper#29]
如果开放平台的access_token过期了，再去请求access_token的时候就会发生下面的错误
`component ticket is invalid hint: [f7sdKA0009hb96]`
然后过了几分钟，就神奇般的又可以正常获取access_token了。？
微信推送的`component_verify_ticket`这个包已经保存进设置的存储目录了啊，数据库也相应更新了。不知道为啥会出这种错误。求解答

**Comment by zoujingli** [comment]
component_verify_ticket 推送有时间间隔

**Comment by Abyss1st** [comment]
问题解决了。
微信有2个appid的推送ticket到我那1个接收地址。然后就覆盖保存了。然后请求开放平台 access_token 的时候就会有一定几率出错。之后对应appid保存推送的ticket就行了
