### ISSUE TITLE
你好，我发现一个问题，关于微信支付异步通知的地方

### ISSUE THREAD

**Issue by maoSting** [zoujingli/WeChatDeveloper#3]
当我支付的时候加密方式是HMAC-SHA256，在微信异步通知的时候，使用\WeChat\Pay->getNotify，这个方法，没有加密方式参数。但是源码使用的是MD5加密方式。所以需要修改一下getNotify这个方法，新增一个加密类型的参数。

**Comment by zoujingli** [comment]
统一使用MD5，版本已经更新
