### ISSUE TITLE
能否增加一个微信付款码支付？

### ISSUE THREAD

**Issue by mirkosir** [zoujingli/WeChatDeveloper#30]
目前源文件和文档里均无法看到 关于微信付款码支付的相关内容。

**Comment by amibk** [comment]
/**
     * 刷卡支付
     * @param array $options
     * @return array
     * @throws \WeChat\Exceptions\InvalidResponseException
     * @throws \WeChat\Exceptions\LocalCacheException
     */
    public function micropay(array $options){
        $url = 'https://api.mch.weixin.qq.com/pay/micropay';
        return $this->callPostApi($url, $options, false, 'MD5');
    }

**Comment by zoujingli** [comment]
已经添加
