### ISSUE TITLE
申请退款的方法调用了统一下单的方法，咦~~~~

### ISSUE THREAD

**Issue by jianfan0709** [zoujingli/WeChatDeveloper#34]
作者不靠谱啊 更bug出来`
    /**
     * 申请退款
     * @param array $options
     * @return array
     * @throws Exceptions\LocalCacheException
     * @throws InvalidResponseException
     */
    public function createRefund(array $options)
    {
        return Order::instance($this->config->get())->create($options);
    }
    /**
     * 查询退款
     * @param array $options
     * @return array
     * @throws Exceptions\LocalCacheException
     * @throws InvalidResponseException
     */
    public function queryRefund(array $options)
    {
        return Order::instance($this->config->get())->query($options);
    }
  #@`https://github.com/zoujingli/WeChatDeveloper/blob/master/WeChat/Pay.php
申请退款的接口怎么就变成了统一下单了呢

**Comment by zoujingli** [comment]
已经处理

**Comment by zoujingli** [comment]
更新下版本就可以了，抱歉哈！
