### ISSUE TITLE
你好，调用小程序生成二维码的时候。返回json，竟然吧图片也输入出去了

### ISSUE THREAD

**Issue by anhuiwj** [zoujingli/WeChatDeveloper#37]
<pre class='xdebug-var-dump' dir='ltr'>
<small>/vendor/zoujingli/wechat-developer/WeMini/Qrcode.php:84:</small><small>string</small> <font color='#cc0000'>'�PNG&#13;&#10;&#10;&#0;&#0;&#0;&#13;IHDR&#0;&#0;&#0;&#0;&#0;&#0;&#0;���&#0;&#0; &#0;IDATx����܇���ωo��Sl1�)Tl��)4+�bҁ �.Cd�*��#W����⸃H��ʠC�]��s�A�XH1[la�M!�/&lt;����~n�7�M�x����������Jߓ+mlll|O������=��������Jߓ+mlll|O������=��������J?0�8�Z��x�&#13;ml�@����ǏO�&gt;�w~~޵k׎o޼y6���V�;���C��ŋ�?��?�x�?����=�����m�������駟�;==�k�8����///�x;]ic�����?�|&gt;�c�;==m�Z��x+]ic����rqrr�7ݸq��tz��[�J?z�ժq{����tyy��ah:�����ih�G���l����{&#39;&#39;&#39;��t�����߸qc1Co�?���.//{�t:��w�}��[kh�G��Ç�~����q��?~|�ڵkǳ�츷���e&#39;&#39;&#39;}�d2i2�������'...</font> <i>(length=51401)</i>
</pre>{"status":"success","msg":"生成二维码成功","data":"jay"}

**Comment by zoujingli** [comment]
这个返回的是二进制文件，需要自己处理下，也可以直接转为base64，再加上png前缀

**Comment by zoujingli** [comment]
`$base64 = base64_encode($result);`
`<img src="data:image/png;base64, {$base64}">`
