### ISSUE TITLE
多台服务器部署项目，access_token 会有失效情况，因为缓存的是本地文件

### ISSUE THREAD

**Issue by chenyongze** [zoujingli/WeChatDeveloper#44]

**Comment by zoujingli** [comment]
ThinkPHP 配置缓存,绑定缓存，参考完 https://gitee.com/zoujingli/WeChatDeveloper/blob/master/_test/config.php------------------ 原始邮件 ------------------
发件人: "Chen,Yongze"<notifications@github.com>
发送时间: 2020年5月18日(星期一) 下午4:46
收件人: "zoujingli/WeChatDeveloper"<WeChatDeveloper@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zoujingli/WeChatDeveloper] 多台服务器部署项目，access_token 会有失效情况，因为缓存的是本地文件 (#44)




 
&mdash;

**Comment by zoujingli** [comment]
可以配置缓存方式，参照：
 https://gitee.com/zoujingli/WeChatDeveloper/blob/master/_test/config.php
