### ISSUE TITLE
不支持支付宝App支付

### ISSUE THREAD

**Issue by Majy999** [zoujingli/WeChatDeveloper#47]
不支持支付宝App支付
位置：vendor/zoujingli/wechat-developer/AliPay/App.php
方法：public function apply($options)
    {
        $this->applyData($options);
        return http_build_query($this->options->get());
    }

**Comment by zoujingli** [comment]
支持

**Comment by zoujingli** [comment]
参见测试案例，返回 query 参数。
https://github.com/zoujingli/WeChatDeveloper/blob/master/_test/alipay-app.php

**Comment by Leslack-hub** [comment]
> 参见测试案例，返回 query 参数。
> https://github.com/zoujingli/WeChatDeveloper/blob/master/_test/alipay-app.php

需要安装支付宝的sdk 发请求吗
