### ISSUE TITLE
发微信立减金这有点问题，我是改成MD5才行，然后注释一段代码

### ISSUE THREAD

**Issue by HIJackone** [zoujingli/WeChatDeveloper#51]
![image](https://user-images.githubusercontent.com/22828772/91960631-b8a71600-ed3c-11ea-9ea8-b0d1714dbed4.png)

注释了这段     $needSignType && ($params['sign_type'] = strtoupper($signType));
    protected function callPostApi($url, array $data, $isCert = false, $signType = 'MD5', $needSignType = true)
改成了MD5

![image](https://user-images.githubusercontent.com/22828772/91960692-cc527c80-ed3c-11ea-8631-a9d3b7459fa6.png)
然后这里查询接口，return_code可能为空（查询频率过快）

**Comment by zoujingli** [comment]
异常的时候，接口返回的 xml 是什么内容？

**Comment by HIJackone** [comment]
curl返回的false
![image](https://user-images.githubusercontent.com/22828772/91967701-286dce80-ed46-11ea-9983-c192440a0001.png)

**Comment by zoujingli** [comment]
如果是 null，那说明是 接口那边 或网络有问题，这里不好处理了
