### ISSUE TITLE
tp5.1 下载引入报错了

### ISSUE THREAD

**Issue by Albbus** [zoujingli/WeChatDeveloper#54]
下载了zip包后 放到了vendor文件夹下，使用的时候用了include  'vendor/WeChatDeveloper/include.php'; 这样的一行代码 然后api请求的时候报错：
[2] ErrorException in Payment.php line 22
include(vendor/WeChatDeveloper/include.php): failed to open stream: No such file or directory

**Comment by zoujingli** [comment]
这是PHP技术基础问题，引入文件的路径错误

**Comment by zoujingli** [comment]
尝试用完整路径
`include app()->getRootPath() . 'vendor/WeChatDeveloper/include.php';`

**Comment by zoujingli** [comment]
另外，建议使用 composer 安装处来处理扩展，否则后期问题多多

**Comment by Albbus** [comment]
> 这是PHP技术基础问题，引入文件的路径错误
好的 感谢，主要是composer 报了个 ‘Your requirements could not be resolved to an installable set of packages.’然后就偷了个懒 谢谢大佬
