### ISSUE TITLE
微信退款通知解密失败

### ISSUE THREAD

**Issue by SoBadBlood** [zoujingli/WeChatDeveloper#56]
一直返回
Array
(
    [0] => 40007
    [1] => 
)

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/103072805-41ee9b00-4601-11eb-8b8a-8f9931c6fa3d.png)
按接口来说，只会返回接收到的数据

**Comment by zoujingli** [comment]
把接收的到数据保存下，然后再进行调试。
从40007编号来看，是说解密失败

**Comment by a1224212544** [comment]
![getNotify](https://user-images.githubusercontent.com/16113123/103073547-c8f04300-4602-11eb-8a0b-56f85fc8f2c7.png)
我是在这里手动打印这行参数看到的结果

**Comment by zoujingli** [comment]
图片看不到，把内容用 标签贴出来

**Comment by a1224212544** [comment]
[https://dhqdjy.ncscloudmedia.com/uploads/png/20201224/56a4071d70951e66c2ee416a7c734e9a.png](url)

**Comment by zoujingli** [comment]
这行是解密异常返回了内容。
在解密之前把内容保存在到文本，然后再手动解密调试

**Comment by zoujingli** [comment]
解密步骤如下：
* 对加密串A做base64解码，得到加密串B
* 对商户key做md5，得到32位小写key* ( key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置 )
* 用key*对加密串B做AES-256-ECB解密（PKCS7Padding）

**Comment by zoujingli** [comment]
退款通知，对于 key 进行md5，没有 base64decode 动作
可以试着调整下 key 值的处理
