### ISSUE TITLE
微信jsapi-v3方法bug

### ISSUE THREAD

**Issue by qinshinailiu** [zoujingli/WeChatDeveloper#59]
WePayV3\Order的create方法生成预支付码之后，再生成sign时错误，会导致前端一直显示 ”支付验证签名失败"
问题出在join方法只在参数间生成“\n"，而文档要求每个参数后都要有个”\n"
希望修复一下

**Comment by zoujingli** [comment]
生成的字符串后面有一个 \n
![image](https://user-images.githubusercontent.com/4349951/113797469-eb5a3680-9783-11eb-9b13-4152d30f7e60.png)

**Comment by zoujingli** [comment]
![image](https://user-images.githubusercontent.com/4349951/113797798-8b17c480-9784-11eb-95fa-db9f5d0519f3.png)
