### ISSUE TITLE
你好，使用sdk给小程序做支付的时候提示签名错误问题

### ISSUE THREAD

**Issue by cys138138** [zoujingli/WeChatDeveloper#6]
// 3. 创建接口实例
        $wechat = new Pay(WxappConfig::getConfig());

        // 4. 组装参数，可以参考官方商户文档
        $options = [
            'body' => '充值',
            'out_trade_no' => OrderService::createOrderSn($userId, $money, '充值'),
            'total_fee' => (int) ($money * 100), //金额转成分
            'openid' => $aUserInfo['openid'],
            'trade_type' => 'JSAPI',
            'notify_url' => url('@api/Notify/payCallback', '', true, true),
                //'spbill_create_ip' => '127.0.0.1',
        ];
        //获取预支付码
        $prepay = $wechat->createOrder($options);
        $result = $wechat->createParamsForJsApi($prepay['prepay_id']);

调用顺序是这样的，发现一个大坑，如果是这样调用小程序发起支付一致都会签名校验出错，改正

修改楼主默认的pay.php中的
    /**
     * 统一下单
     * @param array $options
     * @return array
     * @throws InvalidResponseException
     */
    public function createOrder(array $options, $signType = "MD5") {
        $url = 'https://api.mch.weixin.qq.com/pay/unifiedorder';
        return $this->callPostApi($url, $options, false, $signType);
    }
注意是$signType 这个大坑修复，注意签名类型

**Comment by zoujingli** [comment]
最新版本的统一使用了MD5，不知道有没有解决你的这个问题
