### ISSUE TITLE
【BUG】WeChat/Script.php  getTicket 过期时间是5000  access_token过期时间是7000

### ISSUE THREAD

**Issue by yao978318542** [zoujingli/WeChatDeveloper#60]
![image](https://user-images.githubusercontent.com/18590746/116359784-cc563e00-a831-11eb-9a6f-6b31caca6de4.png)
![image](https://user-images.githubusercontent.com/18590746/116359811-d2e4b580-a831-11eb-9979-bb9747a32a92.png)

**Comment by zoujingli** [comment]
已经统一时间为 7000
