### ISSUE TITLE
使用微信小程序校验一张图片是否含有违法违规内容好像有点问题

### ISSUE THREAD

**Issue by y1834257499** [zoujingli/WeChatDeveloper#63]
校验一张图片是否含有违法违规内容时，微信一直返回：data format error rid: 614f1a94-5399177a-53015afa，最后追踪问题发现请求头错了，然后将参数 $isBuildJson 改为 false 后请求成功
文件路径为：/WeMini/Security.php:39
![image](https://user-images.githubusercontent.com/47782692/134772171-06ee975f-3a79-4038-ac70-fe09470e8b10.png)

**Comment by zoujingli** [comment]
感谢反馈，已经修复
