### ISSUE TITLE
微信支付中APP支付方式，获取支付参数签名

### ISSUE THREAD

**Issue by cocacoffee** [zoujingli/WeChatDeveloper#7]
WePay\Order中，JSAPI和APP两种支付方式，参数签名（package）不同。现在只提供了JSAPI方式的，APP的需要重新拼装参数计算签名，是否考虑添加APP方式的签名方法。
另外，jsapiParams方法中timeStamp和timestamp大小写两种键处于什么考虑？

**Comment by zoujingli** [comment]
微信h5支付与微信jsapi 是不一样的，区别就是这个字段。目前是两个字段 都有，兼容
