### ISSUE TITLE
发送多条信息 但是客服消息比正常回复消息先发 如何解决？

### ISSUE THREAD

**Issue by htwyqjj** [zoujingli/WeChatDeveloper#74]
回复的时候 
$api->text($sendinfo['content'])->reply();
下面在跟着客服发送
$kefu->send($message);
但是为什么用户收到的信息顺序是先客服信息 然后才是正常回复的

**Comment by KuoKongQingYun** [comment]
正常回复是通过http响应回复的，只有你的php执行完成以后才会响应，所以就排在最后。而调用客服接口是通过主动请求腾讯的接口来回复的，你要确定的顺序，就统一用客服消息发

**Comment by zoujingli** [comment]
这是两种不同的消息机制，很难调整顺序，只能自行控制 sleep
