### ISSUE TITLE
v3的签名问题，平台证书直接获取到的商户证书序列号，与实际不符

### ISSUE THREAD

**Issue by allovine** [zoujingli/WeChatDeveloper#79]
不知道为什么平台证书获取到的与实际不符，还是放到config里面比较好，不要动态获取

**Comment by allovine** [comment]
调试了半天，老是签名失败，最后改成从config里面配置下，再获取，就通过了。平台证书生成是用工具生成的，是没问题可以用的

**Comment by zoujingli** [comment]
收到，后面我做一个兼容方案

**Comment by zoujingli** [comment]
已经增加参数
