### ISSUE TITLE
粉丝标签的添加与删除传参均错误.

### ISSUE THREAD

**Issue by amhoho** [zoujingli/WeChatDeveloper#8]
`['openid_list' => $openids, $tagId]);`
应该为:
`['openid_list' => $openids, 'tagid'=>$tagId]);`

否则传的参数成了:
`{"openid_list":["xxx"],"0":106};`

**Comment by zoujingli** [comment]
什么版本，问题所在文件行

**Comment by amhoho** [comment]
@zoujingli 
WeChat\Tags.php
public function batchTagging(array $openids, $tagId)
public function batchUntagging(array $openids, $tagId)

**Comment by zoujingli** [comment]
之前已经修复了，下载新版本
